require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CanBoLopsController do

  # This should return the minimal set of attributes required to create a valid
  # CanBoLop. As you add validations to CanBoLop, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_sinh_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CanBoLopsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all can_bo_lops as @can_bo_lops" do
      can_bo_lop = CanBoLop.create! valid_attributes
      get :index, {}, valid_session
      assigns(:can_bo_lops).should eq([can_bo_lop])
    end
  end

  describe "GET show" do
    it "assigns the requested can_bo_lop as @can_bo_lop" do
      can_bo_lop = CanBoLop.create! valid_attributes
      get :show, {:id => can_bo_lop.to_param}, valid_session
      assigns(:can_bo_lop).should eq(can_bo_lop)
    end
  end

  describe "GET new" do
    it "assigns a new can_bo_lop as @can_bo_lop" do
      get :new, {}, valid_session
      assigns(:can_bo_lop).should be_a_new(CanBoLop)
    end
  end

  describe "GET edit" do
    it "assigns the requested can_bo_lop as @can_bo_lop" do
      can_bo_lop = CanBoLop.create! valid_attributes
      get :edit, {:id => can_bo_lop.to_param}, valid_session
      assigns(:can_bo_lop).should eq(can_bo_lop)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CanBoLop" do
        expect {
          post :create, {:can_bo_lop => valid_attributes}, valid_session
        }.to change(CanBoLop, :count).by(1)
      end

      it "assigns a newly created can_bo_lop as @can_bo_lop" do
        post :create, {:can_bo_lop => valid_attributes}, valid_session
        assigns(:can_bo_lop).should be_a(CanBoLop)
        assigns(:can_bo_lop).should be_persisted
      end

      it "redirects to the created can_bo_lop" do
        post :create, {:can_bo_lop => valid_attributes}, valid_session
        response.should redirect_to(CanBoLop.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved can_bo_lop as @can_bo_lop" do
        # Trigger the behavior that occurs when invalid params are submitted
        CanBoLop.any_instance.stub(:save).and_return(false)
        post :create, {:can_bo_lop => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:can_bo_lop).should be_a_new(CanBoLop)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CanBoLop.any_instance.stub(:save).and_return(false)
        post :create, {:can_bo_lop => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested can_bo_lop" do
        can_bo_lop = CanBoLop.create! valid_attributes
        # Assuming there are no other can_bo_lops in the database, this
        # specifies that the CanBoLop created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CanBoLop.any_instance.should_receive(:update_attributes).with({ "ma_sinh_vien" => "MyString" })
        put :update, {:id => can_bo_lop.to_param, :can_bo_lop => { "ma_sinh_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested can_bo_lop as @can_bo_lop" do
        can_bo_lop = CanBoLop.create! valid_attributes
        put :update, {:id => can_bo_lop.to_param, :can_bo_lop => valid_attributes}, valid_session
        assigns(:can_bo_lop).should eq(can_bo_lop)
      end

      it "redirects to the can_bo_lop" do
        can_bo_lop = CanBoLop.create! valid_attributes
        put :update, {:id => can_bo_lop.to_param, :can_bo_lop => valid_attributes}, valid_session
        response.should redirect_to(can_bo_lop)
      end
    end

    describe "with invalid params" do
      it "assigns the can_bo_lop as @can_bo_lop" do
        can_bo_lop = CanBoLop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CanBoLop.any_instance.stub(:save).and_return(false)
        put :update, {:id => can_bo_lop.to_param, :can_bo_lop => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:can_bo_lop).should eq(can_bo_lop)
      end

      it "re-renders the 'edit' template" do
        can_bo_lop = CanBoLop.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CanBoLop.any_instance.stub(:save).and_return(false)
        put :update, {:id => can_bo_lop.to_param, :can_bo_lop => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested can_bo_lop" do
      can_bo_lop = CanBoLop.create! valid_attributes
      expect {
        delete :destroy, {:id => can_bo_lop.to_param}, valid_session
      }.to change(CanBoLop, :count).by(-1)
    end

    it "redirects to the can_bo_lops list" do
      can_bo_lop = CanBoLop.create! valid_attributes
      delete :destroy, {:id => can_bo_lop.to_param}, valid_session
      response.should redirect_to(can_bo_lops_url)
    end
  end

end
