require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GiangViensController do

  # This should return the minimal set of attributes required to create a valid
  # GiangVien. As you add validations to GiangVien, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ho_ten" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GiangViensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all giang_viens as @giang_viens" do
      giang_vien = GiangVien.create! valid_attributes
      get :index, {}, valid_session
      assigns(:giang_viens).should eq([giang_vien])
    end
  end

  describe "GET show" do
    it "assigns the requested giang_vien as @giang_vien" do
      giang_vien = GiangVien.create! valid_attributes
      get :show, {:id => giang_vien.to_param}, valid_session
      assigns(:giang_vien).should eq(giang_vien)
    end
  end

  describe "GET new" do
    it "assigns a new giang_vien as @giang_vien" do
      get :new, {}, valid_session
      assigns(:giang_vien).should be_a_new(GiangVien)
    end
  end

  describe "GET edit" do
    it "assigns the requested giang_vien as @giang_vien" do
      giang_vien = GiangVien.create! valid_attributes
      get :edit, {:id => giang_vien.to_param}, valid_session
      assigns(:giang_vien).should eq(giang_vien)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new GiangVien" do
        expect {
          post :create, {:giang_vien => valid_attributes}, valid_session
        }.to change(GiangVien, :count).by(1)
      end

      it "assigns a newly created giang_vien as @giang_vien" do
        post :create, {:giang_vien => valid_attributes}, valid_session
        assigns(:giang_vien).should be_a(GiangVien)
        assigns(:giang_vien).should be_persisted
      end

      it "redirects to the created giang_vien" do
        post :create, {:giang_vien => valid_attributes}, valid_session
        response.should redirect_to(GiangVien.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved giang_vien as @giang_vien" do
        # Trigger the behavior that occurs when invalid params are submitted
        GiangVien.any_instance.stub(:save).and_return(false)
        post :create, {:giang_vien => { "ho_ten" => "invalid value" }}, valid_session
        assigns(:giang_vien).should be_a_new(GiangVien)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        GiangVien.any_instance.stub(:save).and_return(false)
        post :create, {:giang_vien => { "ho_ten" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested giang_vien" do
        giang_vien = GiangVien.create! valid_attributes
        # Assuming there are no other giang_viens in the database, this
        # specifies that the GiangVien created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        GiangVien.any_instance.should_receive(:update_attributes).with({ "ho_ten" => "MyString" })
        put :update, {:id => giang_vien.to_param, :giang_vien => { "ho_ten" => "MyString" }}, valid_session
      end

      it "assigns the requested giang_vien as @giang_vien" do
        giang_vien = GiangVien.create! valid_attributes
        put :update, {:id => giang_vien.to_param, :giang_vien => valid_attributes}, valid_session
        assigns(:giang_vien).should eq(giang_vien)
      end

      it "redirects to the giang_vien" do
        giang_vien = GiangVien.create! valid_attributes
        put :update, {:id => giang_vien.to_param, :giang_vien => valid_attributes}, valid_session
        response.should redirect_to(giang_vien)
      end
    end

    describe "with invalid params" do
      it "assigns the giang_vien as @giang_vien" do
        giang_vien = GiangVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GiangVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => giang_vien.to_param, :giang_vien => { "ho_ten" => "invalid value" }}, valid_session
        assigns(:giang_vien).should eq(giang_vien)
      end

      it "re-renders the 'edit' template" do
        giang_vien = GiangVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        GiangVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => giang_vien.to_param, :giang_vien => { "ho_ten" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested giang_vien" do
      giang_vien = GiangVien.create! valid_attributes
      expect {
        delete :destroy, {:id => giang_vien.to_param}, valid_session
      }.to change(GiangVien, :count).by(-1)
    end

    it "redirects to the giang_viens list" do
      giang_vien = GiangVien.create! valid_attributes
      delete :destroy, {:id => giang_vien.to_param}, valid_session
      response.should redirect_to(giang_viens_url)
    end
  end

end
