require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe KienNghisController do

  # This should return the minimal set of attributes required to create a valid
  # KienNghi. As you add validations to KienNghi, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_sinh_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # KienNghisController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all kien_nghis as @kien_nghis" do
      kien_nghi = KienNghi.create! valid_attributes
      get :index, {}, valid_session
      assigns(:kien_nghis).should eq([kien_nghi])
    end
  end

  describe "GET show" do
    it "assigns the requested kien_nghi as @kien_nghi" do
      kien_nghi = KienNghi.create! valid_attributes
      get :show, {:id => kien_nghi.to_param}, valid_session
      assigns(:kien_nghi).should eq(kien_nghi)
    end
  end

  describe "GET new" do
    it "assigns a new kien_nghi as @kien_nghi" do
      get :new, {}, valid_session
      assigns(:kien_nghi).should be_a_new(KienNghi)
    end
  end

  describe "GET edit" do
    it "assigns the requested kien_nghi as @kien_nghi" do
      kien_nghi = KienNghi.create! valid_attributes
      get :edit, {:id => kien_nghi.to_param}, valid_session
      assigns(:kien_nghi).should eq(kien_nghi)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new KienNghi" do
        expect {
          post :create, {:kien_nghi => valid_attributes}, valid_session
        }.to change(KienNghi, :count).by(1)
      end

      it "assigns a newly created kien_nghi as @kien_nghi" do
        post :create, {:kien_nghi => valid_attributes}, valid_session
        assigns(:kien_nghi).should be_a(KienNghi)
        assigns(:kien_nghi).should be_persisted
      end

      it "redirects to the created kien_nghi" do
        post :create, {:kien_nghi => valid_attributes}, valid_session
        response.should redirect_to(KienNghi.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved kien_nghi as @kien_nghi" do
        # Trigger the behavior that occurs when invalid params are submitted
        KienNghi.any_instance.stub(:save).and_return(false)
        post :create, {:kien_nghi => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:kien_nghi).should be_a_new(KienNghi)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        KienNghi.any_instance.stub(:save).and_return(false)
        post :create, {:kien_nghi => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested kien_nghi" do
        kien_nghi = KienNghi.create! valid_attributes
        # Assuming there are no other kien_nghis in the database, this
        # specifies that the KienNghi created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        KienNghi.any_instance.should_receive(:update_attributes).with({ "ma_sinh_vien" => "MyString" })
        put :update, {:id => kien_nghi.to_param, :kien_nghi => { "ma_sinh_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested kien_nghi as @kien_nghi" do
        kien_nghi = KienNghi.create! valid_attributes
        put :update, {:id => kien_nghi.to_param, :kien_nghi => valid_attributes}, valid_session
        assigns(:kien_nghi).should eq(kien_nghi)
      end

      it "redirects to the kien_nghi" do
        kien_nghi = KienNghi.create! valid_attributes
        put :update, {:id => kien_nghi.to_param, :kien_nghi => valid_attributes}, valid_session
        response.should redirect_to(kien_nghi)
      end
    end

    describe "with invalid params" do
      it "assigns the kien_nghi as @kien_nghi" do
        kien_nghi = KienNghi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KienNghi.any_instance.stub(:save).and_return(false)
        put :update, {:id => kien_nghi.to_param, :kien_nghi => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:kien_nghi).should eq(kien_nghi)
      end

      it "re-renders the 'edit' template" do
        kien_nghi = KienNghi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        KienNghi.any_instance.stub(:save).and_return(false)
        put :update, {:id => kien_nghi.to_param, :kien_nghi => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested kien_nghi" do
      kien_nghi = KienNghi.create! valid_attributes
      expect {
        delete :destroy, {:id => kien_nghi.to_param}, valid_session
      }.to change(KienNghi, :count).by(-1)
    end

    it "redirects to the kien_nghis list" do
      kien_nghi = KienNghi.create! valid_attributes
      delete :destroy, {:id => kien_nghi.to_param}, valid_session
      response.should redirect_to(kien_nghis_url)
    end
  end

end
