require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LichTrinhGiangDaysController do

  # This should return the minimal set of attributes required to create a valid
  # LichTrinhGiangDay. As you add validations to LichTrinhGiangDay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_lop" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LichTrinhGiangDaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lich_trinh_giang_days as @lich_trinh_giang_days" do
      lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lich_trinh_giang_days).should eq([lich_trinh_giang_day])
    end
  end

  describe "GET show" do
    it "assigns the requested lich_trinh_giang_day as @lich_trinh_giang_day" do
      lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
      get :show, {:id => lich_trinh_giang_day.to_param}, valid_session
      assigns(:lich_trinh_giang_day).should eq(lich_trinh_giang_day)
    end
  end

  describe "GET new" do
    it "assigns a new lich_trinh_giang_day as @lich_trinh_giang_day" do
      get :new, {}, valid_session
      assigns(:lich_trinh_giang_day).should be_a_new(LichTrinhGiangDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested lich_trinh_giang_day as @lich_trinh_giang_day" do
      lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
      get :edit, {:id => lich_trinh_giang_day.to_param}, valid_session
      assigns(:lich_trinh_giang_day).should eq(lich_trinh_giang_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LichTrinhGiangDay" do
        expect {
          post :create, {:lich_trinh_giang_day => valid_attributes}, valid_session
        }.to change(LichTrinhGiangDay, :count).by(1)
      end

      it "assigns a newly created lich_trinh_giang_day as @lich_trinh_giang_day" do
        post :create, {:lich_trinh_giang_day => valid_attributes}, valid_session
        assigns(:lich_trinh_giang_day).should be_a(LichTrinhGiangDay)
        assigns(:lich_trinh_giang_day).should be_persisted
      end

      it "redirects to the created lich_trinh_giang_day" do
        post :create, {:lich_trinh_giang_day => valid_attributes}, valid_session
        response.should redirect_to(LichTrinhGiangDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lich_trinh_giang_day as @lich_trinh_giang_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        LichTrinhGiangDay.any_instance.stub(:save).and_return(false)
        post :create, {:lich_trinh_giang_day => { "ma_lop" => "invalid value" }}, valid_session
        assigns(:lich_trinh_giang_day).should be_a_new(LichTrinhGiangDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LichTrinhGiangDay.any_instance.stub(:save).and_return(false)
        post :create, {:lich_trinh_giang_day => { "ma_lop" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lich_trinh_giang_day" do
        lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
        # Assuming there are no other lich_trinh_giang_days in the database, this
        # specifies that the LichTrinhGiangDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LichTrinhGiangDay.any_instance.should_receive(:update_attributes).with({ "ma_lop" => "MyString" })
        put :update, {:id => lich_trinh_giang_day.to_param, :lich_trinh_giang_day => { "ma_lop" => "MyString" }}, valid_session
      end

      it "assigns the requested lich_trinh_giang_day as @lich_trinh_giang_day" do
        lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
        put :update, {:id => lich_trinh_giang_day.to_param, :lich_trinh_giang_day => valid_attributes}, valid_session
        assigns(:lich_trinh_giang_day).should eq(lich_trinh_giang_day)
      end

      it "redirects to the lich_trinh_giang_day" do
        lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
        put :update, {:id => lich_trinh_giang_day.to_param, :lich_trinh_giang_day => valid_attributes}, valid_session
        response.should redirect_to(lich_trinh_giang_day)
      end
    end

    describe "with invalid params" do
      it "assigns the lich_trinh_giang_day as @lich_trinh_giang_day" do
        lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LichTrinhGiangDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => lich_trinh_giang_day.to_param, :lich_trinh_giang_day => { "ma_lop" => "invalid value" }}, valid_session
        assigns(:lich_trinh_giang_day).should eq(lich_trinh_giang_day)
      end

      it "re-renders the 'edit' template" do
        lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LichTrinhGiangDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => lich_trinh_giang_day.to_param, :lich_trinh_giang_day => { "ma_lop" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lich_trinh_giang_day" do
      lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
      expect {
        delete :destroy, {:id => lich_trinh_giang_day.to_param}, valid_session
      }.to change(LichTrinhGiangDay, :count).by(-1)
    end

    it "redirects to the lich_trinh_giang_days list" do
      lich_trinh_giang_day = LichTrinhGiangDay.create! valid_attributes
      delete :destroy, {:id => lich_trinh_giang_day.to_param}, valid_session
      response.should redirect_to(lich_trinh_giang_days_url)
    end
  end

end
