require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LopMonHocSinhViensController do

  # This should return the minimal set of attributes required to create a valid
  # LopMonHocSinhVien. As you add validations to LopMonHocSinhVien, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_sinh_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LopMonHocSinhViensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all lop_mon_hoc_sinh_viens as @lop_mon_hoc_sinh_viens" do
      lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
      get :index, {}, valid_session
      assigns(:lop_mon_hoc_sinh_viens).should eq([lop_mon_hoc_sinh_vien])
    end
  end

  describe "GET show" do
    it "assigns the requested lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
      lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
      get :show, {:id => lop_mon_hoc_sinh_vien.to_param}, valid_session
      assigns(:lop_mon_hoc_sinh_vien).should eq(lop_mon_hoc_sinh_vien)
    end
  end

  describe "GET new" do
    it "assigns a new lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
      get :new, {}, valid_session
      assigns(:lop_mon_hoc_sinh_vien).should be_a_new(LopMonHocSinhVien)
    end
  end

  describe "GET edit" do
    it "assigns the requested lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
      lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
      get :edit, {:id => lop_mon_hoc_sinh_vien.to_param}, valid_session
      assigns(:lop_mon_hoc_sinh_vien).should eq(lop_mon_hoc_sinh_vien)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LopMonHocSinhVien" do
        expect {
          post :create, {:lop_mon_hoc_sinh_vien => valid_attributes}, valid_session
        }.to change(LopMonHocSinhVien, :count).by(1)
      end

      it "assigns a newly created lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
        post :create, {:lop_mon_hoc_sinh_vien => valid_attributes}, valid_session
        assigns(:lop_mon_hoc_sinh_vien).should be_a(LopMonHocSinhVien)
        assigns(:lop_mon_hoc_sinh_vien).should be_persisted
      end

      it "redirects to the created lop_mon_hoc_sinh_vien" do
        post :create, {:lop_mon_hoc_sinh_vien => valid_attributes}, valid_session
        response.should redirect_to(LopMonHocSinhVien.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
        # Trigger the behavior that occurs when invalid params are submitted
        LopMonHocSinhVien.any_instance.stub(:save).and_return(false)
        post :create, {:lop_mon_hoc_sinh_vien => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:lop_mon_hoc_sinh_vien).should be_a_new(LopMonHocSinhVien)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LopMonHocSinhVien.any_instance.stub(:save).and_return(false)
        post :create, {:lop_mon_hoc_sinh_vien => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested lop_mon_hoc_sinh_vien" do
        lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
        # Assuming there are no other lop_mon_hoc_sinh_viens in the database, this
        # specifies that the LopMonHocSinhVien created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LopMonHocSinhVien.any_instance.should_receive(:update_attributes).with({ "ma_sinh_vien" => "MyString" })
        put :update, {:id => lop_mon_hoc_sinh_vien.to_param, :lop_mon_hoc_sinh_vien => { "ma_sinh_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
        lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
        put :update, {:id => lop_mon_hoc_sinh_vien.to_param, :lop_mon_hoc_sinh_vien => valid_attributes}, valid_session
        assigns(:lop_mon_hoc_sinh_vien).should eq(lop_mon_hoc_sinh_vien)
      end

      it "redirects to the lop_mon_hoc_sinh_vien" do
        lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
        put :update, {:id => lop_mon_hoc_sinh_vien.to_param, :lop_mon_hoc_sinh_vien => valid_attributes}, valid_session
        response.should redirect_to(lop_mon_hoc_sinh_vien)
      end
    end

    describe "with invalid params" do
      it "assigns the lop_mon_hoc_sinh_vien as @lop_mon_hoc_sinh_vien" do
        lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LopMonHocSinhVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => lop_mon_hoc_sinh_vien.to_param, :lop_mon_hoc_sinh_vien => { "ma_sinh_vien" => "invalid value" }}, valid_session
        assigns(:lop_mon_hoc_sinh_vien).should eq(lop_mon_hoc_sinh_vien)
      end

      it "re-renders the 'edit' template" do
        lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LopMonHocSinhVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => lop_mon_hoc_sinh_vien.to_param, :lop_mon_hoc_sinh_vien => { "ma_sinh_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested lop_mon_hoc_sinh_vien" do
      lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
      expect {
        delete :destroy, {:id => lop_mon_hoc_sinh_vien.to_param}, valid_session
      }.to change(LopMonHocSinhVien, :count).by(-1)
    end

    it "redirects to the lop_mon_hoc_sinh_viens list" do
      lop_mon_hoc_sinh_vien = LopMonHocSinhVien.create! valid_attributes
      delete :destroy, {:id => lop_mon_hoc_sinh_vien.to_param}, valid_session
      response.should redirect_to(lop_mon_hoc_sinh_viens_url)
    end
  end

end
