require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NghiDaysController do

  # This should return the minimal set of attributes required to create a valid
  # NghiDay. As you add validations to NghiDay, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_giang_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NghiDaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all nghi_days as @nghi_days" do
      nghi_day = NghiDay.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nghi_days).should eq([nghi_day])
    end
  end

  describe "GET show" do
    it "assigns the requested nghi_day as @nghi_day" do
      nghi_day = NghiDay.create! valid_attributes
      get :show, {:id => nghi_day.to_param}, valid_session
      assigns(:nghi_day).should eq(nghi_day)
    end
  end

  describe "GET new" do
    it "assigns a new nghi_day as @nghi_day" do
      get :new, {}, valid_session
      assigns(:nghi_day).should be_a_new(NghiDay)
    end
  end

  describe "GET edit" do
    it "assigns the requested nghi_day as @nghi_day" do
      nghi_day = NghiDay.create! valid_attributes
      get :edit, {:id => nghi_day.to_param}, valid_session
      assigns(:nghi_day).should eq(nghi_day)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NghiDay" do
        expect {
          post :create, {:nghi_day => valid_attributes}, valid_session
        }.to change(NghiDay, :count).by(1)
      end

      it "assigns a newly created nghi_day as @nghi_day" do
        post :create, {:nghi_day => valid_attributes}, valid_session
        assigns(:nghi_day).should be_a(NghiDay)
        assigns(:nghi_day).should be_persisted
      end

      it "redirects to the created nghi_day" do
        post :create, {:nghi_day => valid_attributes}, valid_session
        response.should redirect_to(NghiDay.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nghi_day as @nghi_day" do
        # Trigger the behavior that occurs when invalid params are submitted
        NghiDay.any_instance.stub(:save).and_return(false)
        post :create, {:nghi_day => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:nghi_day).should be_a_new(NghiDay)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NghiDay.any_instance.stub(:save).and_return(false)
        post :create, {:nghi_day => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nghi_day" do
        nghi_day = NghiDay.create! valid_attributes
        # Assuming there are no other nghi_days in the database, this
        # specifies that the NghiDay created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NghiDay.any_instance.should_receive(:update_attributes).with({ "ma_giang_vien" => "MyString" })
        put :update, {:id => nghi_day.to_param, :nghi_day => { "ma_giang_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested nghi_day as @nghi_day" do
        nghi_day = NghiDay.create! valid_attributes
        put :update, {:id => nghi_day.to_param, :nghi_day => valid_attributes}, valid_session
        assigns(:nghi_day).should eq(nghi_day)
      end

      it "redirects to the nghi_day" do
        nghi_day = NghiDay.create! valid_attributes
        put :update, {:id => nghi_day.to_param, :nghi_day => valid_attributes}, valid_session
        response.should redirect_to(nghi_day)
      end
    end

    describe "with invalid params" do
      it "assigns the nghi_day as @nghi_day" do
        nghi_day = NghiDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NghiDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => nghi_day.to_param, :nghi_day => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:nghi_day).should eq(nghi_day)
      end

      it "re-renders the 'edit' template" do
        nghi_day = NghiDay.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NghiDay.any_instance.stub(:save).and_return(false)
        put :update, {:id => nghi_day.to_param, :nghi_day => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nghi_day" do
      nghi_day = NghiDay.create! valid_attributes
      expect {
        delete :destroy, {:id => nghi_day.to_param}, valid_session
      }.to change(NghiDay, :count).by(-1)
    end

    it "redirects to the nghi_days list" do
      nghi_day = NghiDay.create! valid_attributes
      delete :destroy, {:id => nghi_day.to_param}, valid_session
      response.should redirect_to(nghi_days_url)
    end
  end

end
