require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NhatKiesController do

  # This should return the minimal set of attributes required to create a valid
  # NhatKy. As you add validations to NhatKy, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_nguoi_dung" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NhatKiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all nhat_kies as @nhat_kies" do
      nhat_ky = NhatKy.create! valid_attributes
      get :index, {}, valid_session
      assigns(:nhat_kies).should eq([nhat_ky])
    end
  end

  describe "GET show" do
    it "assigns the requested nhat_ky as @nhat_ky" do
      nhat_ky = NhatKy.create! valid_attributes
      get :show, {:id => nhat_ky.to_param}, valid_session
      assigns(:nhat_ky).should eq(nhat_ky)
    end
  end

  describe "GET new" do
    it "assigns a new nhat_ky as @nhat_ky" do
      get :new, {}, valid_session
      assigns(:nhat_ky).should be_a_new(NhatKy)
    end
  end

  describe "GET edit" do
    it "assigns the requested nhat_ky as @nhat_ky" do
      nhat_ky = NhatKy.create! valid_attributes
      get :edit, {:id => nhat_ky.to_param}, valid_session
      assigns(:nhat_ky).should eq(nhat_ky)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new NhatKy" do
        expect {
          post :create, {:nhat_ky => valid_attributes}, valid_session
        }.to change(NhatKy, :count).by(1)
      end

      it "assigns a newly created nhat_ky as @nhat_ky" do
        post :create, {:nhat_ky => valid_attributes}, valid_session
        assigns(:nhat_ky).should be_a(NhatKy)
        assigns(:nhat_ky).should be_persisted
      end

      it "redirects to the created nhat_ky" do
        post :create, {:nhat_ky => valid_attributes}, valid_session
        response.should redirect_to(NhatKy.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved nhat_ky as @nhat_ky" do
        # Trigger the behavior that occurs when invalid params are submitted
        NhatKy.any_instance.stub(:save).and_return(false)
        post :create, {:nhat_ky => { "ma_nguoi_dung" => "invalid value" }}, valid_session
        assigns(:nhat_ky).should be_a_new(NhatKy)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        NhatKy.any_instance.stub(:save).and_return(false)
        post :create, {:nhat_ky => { "ma_nguoi_dung" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested nhat_ky" do
        nhat_ky = NhatKy.create! valid_attributes
        # Assuming there are no other nhat_kies in the database, this
        # specifies that the NhatKy created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        NhatKy.any_instance.should_receive(:update_attributes).with({ "ma_nguoi_dung" => "MyString" })
        put :update, {:id => nhat_ky.to_param, :nhat_ky => { "ma_nguoi_dung" => "MyString" }}, valid_session
      end

      it "assigns the requested nhat_ky as @nhat_ky" do
        nhat_ky = NhatKy.create! valid_attributes
        put :update, {:id => nhat_ky.to_param, :nhat_ky => valid_attributes}, valid_session
        assigns(:nhat_ky).should eq(nhat_ky)
      end

      it "redirects to the nhat_ky" do
        nhat_ky = NhatKy.create! valid_attributes
        put :update, {:id => nhat_ky.to_param, :nhat_ky => valid_attributes}, valid_session
        response.should redirect_to(nhat_ky)
      end
    end

    describe "with invalid params" do
      it "assigns the nhat_ky as @nhat_ky" do
        nhat_ky = NhatKy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NhatKy.any_instance.stub(:save).and_return(false)
        put :update, {:id => nhat_ky.to_param, :nhat_ky => { "ma_nguoi_dung" => "invalid value" }}, valid_session
        assigns(:nhat_ky).should eq(nhat_ky)
      end

      it "re-renders the 'edit' template" do
        nhat_ky = NhatKy.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        NhatKy.any_instance.stub(:save).and_return(false)
        put :update, {:id => nhat_ky.to_param, :nhat_ky => { "ma_nguoi_dung" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested nhat_ky" do
      nhat_ky = NhatKy.create! valid_attributes
      expect {
        delete :destroy, {:id => nhat_ky.to_param}, valid_session
      }.to change(NhatKy, :count).by(-1)
    end

    it "redirects to the nhat_kies list" do
      nhat_ky = NhatKy.create! valid_attributes
      delete :destroy, {:id => nhat_ky.to_param}, valid_session
      response.should redirect_to(nhat_kies_url)
    end
  end

end
