require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RaSomVaoMuonsController do

  # This should return the minimal set of attributes required to create a valid
  # RaSomVaoMuon. As you add validations to RaSomVaoMuon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_giang_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RaSomVaoMuonsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ra_som_vao_muons as @ra_som_vao_muons" do
      ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ra_som_vao_muons).should eq([ra_som_vao_muon])
    end
  end

  describe "GET show" do
    it "assigns the requested ra_som_vao_muon as @ra_som_vao_muon" do
      ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
      get :show, {:id => ra_som_vao_muon.to_param}, valid_session
      assigns(:ra_som_vao_muon).should eq(ra_som_vao_muon)
    end
  end

  describe "GET new" do
    it "assigns a new ra_som_vao_muon as @ra_som_vao_muon" do
      get :new, {}, valid_session
      assigns(:ra_som_vao_muon).should be_a_new(RaSomVaoMuon)
    end
  end

  describe "GET edit" do
    it "assigns the requested ra_som_vao_muon as @ra_som_vao_muon" do
      ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
      get :edit, {:id => ra_som_vao_muon.to_param}, valid_session
      assigns(:ra_som_vao_muon).should eq(ra_som_vao_muon)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RaSomVaoMuon" do
        expect {
          post :create, {:ra_som_vao_muon => valid_attributes}, valid_session
        }.to change(RaSomVaoMuon, :count).by(1)
      end

      it "assigns a newly created ra_som_vao_muon as @ra_som_vao_muon" do
        post :create, {:ra_som_vao_muon => valid_attributes}, valid_session
        assigns(:ra_som_vao_muon).should be_a(RaSomVaoMuon)
        assigns(:ra_som_vao_muon).should be_persisted
      end

      it "redirects to the created ra_som_vao_muon" do
        post :create, {:ra_som_vao_muon => valid_attributes}, valid_session
        response.should redirect_to(RaSomVaoMuon.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ra_som_vao_muon as @ra_som_vao_muon" do
        # Trigger the behavior that occurs when invalid params are submitted
        RaSomVaoMuon.any_instance.stub(:save).and_return(false)
        post :create, {:ra_som_vao_muon => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:ra_som_vao_muon).should be_a_new(RaSomVaoMuon)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RaSomVaoMuon.any_instance.stub(:save).and_return(false)
        post :create, {:ra_som_vao_muon => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ra_som_vao_muon" do
        ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
        # Assuming there are no other ra_som_vao_muons in the database, this
        # specifies that the RaSomVaoMuon created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RaSomVaoMuon.any_instance.should_receive(:update_attributes).with({ "ma_giang_vien" => "MyString" })
        put :update, {:id => ra_som_vao_muon.to_param, :ra_som_vao_muon => { "ma_giang_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested ra_som_vao_muon as @ra_som_vao_muon" do
        ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
        put :update, {:id => ra_som_vao_muon.to_param, :ra_som_vao_muon => valid_attributes}, valid_session
        assigns(:ra_som_vao_muon).should eq(ra_som_vao_muon)
      end

      it "redirects to the ra_som_vao_muon" do
        ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
        put :update, {:id => ra_som_vao_muon.to_param, :ra_som_vao_muon => valid_attributes}, valid_session
        response.should redirect_to(ra_som_vao_muon)
      end
    end

    describe "with invalid params" do
      it "assigns the ra_som_vao_muon as @ra_som_vao_muon" do
        ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RaSomVaoMuon.any_instance.stub(:save).and_return(false)
        put :update, {:id => ra_som_vao_muon.to_param, :ra_som_vao_muon => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:ra_som_vao_muon).should eq(ra_som_vao_muon)
      end

      it "re-renders the 'edit' template" do
        ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RaSomVaoMuon.any_instance.stub(:save).and_return(false)
        put :update, {:id => ra_som_vao_muon.to_param, :ra_som_vao_muon => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ra_som_vao_muon" do
      ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
      expect {
        delete :destroy, {:id => ra_som_vao_muon.to_param}, valid_session
      }.to change(RaSomVaoMuon, :count).by(-1)
    end

    it "redirects to the ra_som_vao_muons list" do
      ra_som_vao_muon = RaSomVaoMuon.create! valid_attributes
      delete :destroy, {:id => ra_som_vao_muon.to_param}, valid_session
      response.should redirect_to(ra_som_vao_muons_url)
    end
  end

end
