require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TkbGiangViensController do

  # This should return the minimal set of attributes required to create a valid
  # TkbGiangVien. As you add validations to TkbGiangVien, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "ma_giang_vien" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TkbGiangViensController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all tkb_giang_viens as @tkb_giang_viens" do
      tkb_giang_vien = TkbGiangVien.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tkb_giang_viens).should eq([tkb_giang_vien])
    end
  end

  describe "GET show" do
    it "assigns the requested tkb_giang_vien as @tkb_giang_vien" do
      tkb_giang_vien = TkbGiangVien.create! valid_attributes
      get :show, {:id => tkb_giang_vien.to_param}, valid_session
      assigns(:tkb_giang_vien).should eq(tkb_giang_vien)
    end
  end

  describe "GET new" do
    it "assigns a new tkb_giang_vien as @tkb_giang_vien" do
      get :new, {}, valid_session
      assigns(:tkb_giang_vien).should be_a_new(TkbGiangVien)
    end
  end

  describe "GET edit" do
    it "assigns the requested tkb_giang_vien as @tkb_giang_vien" do
      tkb_giang_vien = TkbGiangVien.create! valid_attributes
      get :edit, {:id => tkb_giang_vien.to_param}, valid_session
      assigns(:tkb_giang_vien).should eq(tkb_giang_vien)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TkbGiangVien" do
        expect {
          post :create, {:tkb_giang_vien => valid_attributes}, valid_session
        }.to change(TkbGiangVien, :count).by(1)
      end

      it "assigns a newly created tkb_giang_vien as @tkb_giang_vien" do
        post :create, {:tkb_giang_vien => valid_attributes}, valid_session
        assigns(:tkb_giang_vien).should be_a(TkbGiangVien)
        assigns(:tkb_giang_vien).should be_persisted
      end

      it "redirects to the created tkb_giang_vien" do
        post :create, {:tkb_giang_vien => valid_attributes}, valid_session
        response.should redirect_to(TkbGiangVien.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tkb_giang_vien as @tkb_giang_vien" do
        # Trigger the behavior that occurs when invalid params are submitted
        TkbGiangVien.any_instance.stub(:save).and_return(false)
        post :create, {:tkb_giang_vien => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:tkb_giang_vien).should be_a_new(TkbGiangVien)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TkbGiangVien.any_instance.stub(:save).and_return(false)
        post :create, {:tkb_giang_vien => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tkb_giang_vien" do
        tkb_giang_vien = TkbGiangVien.create! valid_attributes
        # Assuming there are no other tkb_giang_viens in the database, this
        # specifies that the TkbGiangVien created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TkbGiangVien.any_instance.should_receive(:update_attributes).with({ "ma_giang_vien" => "MyString" })
        put :update, {:id => tkb_giang_vien.to_param, :tkb_giang_vien => { "ma_giang_vien" => "MyString" }}, valid_session
      end

      it "assigns the requested tkb_giang_vien as @tkb_giang_vien" do
        tkb_giang_vien = TkbGiangVien.create! valid_attributes
        put :update, {:id => tkb_giang_vien.to_param, :tkb_giang_vien => valid_attributes}, valid_session
        assigns(:tkb_giang_vien).should eq(tkb_giang_vien)
      end

      it "redirects to the tkb_giang_vien" do
        tkb_giang_vien = TkbGiangVien.create! valid_attributes
        put :update, {:id => tkb_giang_vien.to_param, :tkb_giang_vien => valid_attributes}, valid_session
        response.should redirect_to(tkb_giang_vien)
      end
    end

    describe "with invalid params" do
      it "assigns the tkb_giang_vien as @tkb_giang_vien" do
        tkb_giang_vien = TkbGiangVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TkbGiangVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => tkb_giang_vien.to_param, :tkb_giang_vien => { "ma_giang_vien" => "invalid value" }}, valid_session
        assigns(:tkb_giang_vien).should eq(tkb_giang_vien)
      end

      it "re-renders the 'edit' template" do
        tkb_giang_vien = TkbGiangVien.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TkbGiangVien.any_instance.stub(:save).and_return(false)
        put :update, {:id => tkb_giang_vien.to_param, :tkb_giang_vien => { "ma_giang_vien" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tkb_giang_vien" do
      tkb_giang_vien = TkbGiangVien.create! valid_attributes
      expect {
        delete :destroy, {:id => tkb_giang_vien.to_param}, valid_session
      }.to change(TkbGiangVien, :count).by(-1)
    end

    it "redirects to the tkb_giang_viens list" do
      tkb_giang_vien = TkbGiangVien.create! valid_attributes
      delete :destroy, {:id => tkb_giang_vien.to_param}, valid_session
      response.should redirect_to(tkb_giang_viens_url)
    end
  end

end
